all: bush max sum strcat maxlength

bush: bush.c
	gcc bush.c -o bush

max: max.c
	gcc max.c -o max

sum: sum.c
	gcc sum.c -o sum

strcat: strcat.c
	gcc strcat.c -o strcat

maxlength: maxlength.c
	gcc maxlength.c -o maxlength

clean:
	rm -rf *.o bush max sum strcat maxlength
